# Generated by Django 2.2.2 on 2019-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nombre')),
                ('description', models.TextField(max_length=300, verbose_name='descripción')),
                ('summary', models.TextField(max_length=500, verbose_name='resumen')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='fecha de creación')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='es recomendada')),
                ('is_active', models.BooleanField(default=False, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'película',
                'verbose_name_plural': 'películas',
                'ordering': ['-created_at'],
            },
        ),
    ]
